/**
 * CorePlugin.BackendDevServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindGapsModelPerson } from './findGapsModelPerson';
import { FindGapsModelParticipant } from './findGapsModelParticipant';


export interface FindGapsModel { 
    teachers?: Array<FindGapsModelPerson> | null;
    students?: Array<FindGapsModelPerson> | null;
    teacherParticipants?: Array<FindGapsModelParticipant> | null;
    studentParticipants?: Array<FindGapsModelParticipant> | null;
    from?: string;
    to?: string;
    startToleranceMinutes?: number;
    endToleranceMinutes?: number;
    minDurationMinutes?: number;
}

