/**
 * CorePlugin.BackendDevServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MeetingModel { 
    teacherIds?: Array<number> | null;
    studentIds?: Array<number> | null;
    subject?: string | null;
    description?: string | null;
    from?: string;
    to?: string;
    location?: string | null;
}

